/**
 * Portable Solution Comparison Tool — data only.
 * Exposes window.VPC_COMPARISON_DATA. Edit this file for routine data updates.
 */
(function () {
  'use strict';

  window.VPC_COMPARISON_DATA = {
    specRows: [
      { key: 'bedCapacity', label: 'Bed Capacity' },
      { key: 'extDims', label: 'External Footprint' },
      { key: 'intDims', label: 'Internal Floorspace' },
      { key: 'setup', label: 'Setup time & number of personnel required' },
      { key: 'wind', label: 'Wind resistance rating' },
      { key: 'snow', label: 'Snow load' },
      { key: 'fire', label: 'Fire Resistance Rating' },
      { key: 'ground', label: 'Recommended ground surface' },
      { key: 'lifespan', label: 'Expected lifespan' },
      { key: 'repair', label: 'Repair expectations & procedures' },
    ],
    vendors: [
      {
        name: 'BLU-MED',
        logo: 'logos/blumed.png',
        products: [
          { id: 'blumed-2032', name: '2032.5 XPH', type: 'shelter' },
          { id: 'blumed-2039', name: '2039 XPH', type: 'shelter' },
        ],
      },
      {
        name: 'DLX',
        logo: 'logos/dlx.png',
        products: [
          { id: 'dlx-asap18', name: 'ASAP18',  type: 'shelter', tested: false },
          { id: 'dlx-x8',     name: 'X-8',     type: 'shelter', tested: false },
          { id: 'dlx-x16',    name: 'X-16',    type: 'shelter', tested: false },
          { id: 'dlx-x24',    name: 'X-24',    type: 'shelter' },
          { id: 'dlx-x24sc',  name: 'X-24SC',  type: 'shelter', tested: false },
          { id: 'dlx-x32',    name: 'X-32',    type: 'shelter' },
          { id: 'dlx-x40',    name: 'X-40',    type: 'shelter', tested: false },
          { id: 'dlx-xhub',   name: 'X-Hub',   type: 'connector' },
        ],
      },
      {
        name: 'HDT',
        logo: 'logos/hdt.png',
        products: [
          { id: 'hdt-305', name: 'Base-X 305', type: 'shelter' },
          {
            id: 'hdt-8d36',
            name: 'Base-X 8D36',
            type: 'shelter',
            infoText:
              'HDT does not produce a small connector. The 8D36 can serve a connector role, but is sized as a full shelter and is listed as such.',
          },
        ],
      },
      {
        name: 'Western Shelter',
        logo: 'logos/western-shelter.png',
        products: [
          { id: 'ws-gk20', name: 'GK-20', type: 'shelter' },
          { id: 'ws-gk1935', name: 'GK-1935', type: 'shelter' },
          { id: 'ws-gk2360', name: 'GateKeeper 2360', type: 'shelter', tested: false },
          { id: 'ws-gk2342', name: 'GateKeeper 2342', type: 'shelter', tested: false },
          { id: 'ws-guardian-2032', name: 'Guardian 2032', type: 'shelter', tested: false },
          { id: 'ws-guardian-3065', name: 'Guardian 3065', type: 'shelter', tested: false },
        ],
      },
      {
        name: 'ZUMRO',
        logo: 'logos/zumro.png',
        products: [
          { id: 'zumro-400', name: 'Model 400', type: 'shelter' },
          { id: 'zumro-600', name: 'Model 600', type: 'shelter' },
          { id: 'zumro-216', name: 'Model 216', type: 'shelter', tested: false },
          { id: 'zumro-900', name: 'Model 900', type: 'shelter', tested: false },
          {
            id: 'zumro-airlock',
            name: 'External Airlock Shelter System',
            type: 'connector',
            tested: false,
          },
          { id: 'zumro-quad', name: 'QUAD Interface', type: 'connector' },
        ],
      },
      {
        name: 'Craftsmen',
        logo: 'logos/craftsmen.png',
        structure: 'hard-sided',
        products: [
          {
            id: 'craftsmen-8bed-icu',
            name: '8-Bed ICU Trailer',
            type: 'shelter',
            tested: false,
          },
        ],
      },
      {
        name: 'FORTS',
        logo: 'logos/forts.png',
        structure: 'hard-sided',
        products: [
          {
            id: 'forts-38',
            name: 'Model 38',
            type: 'shelter',
            tested: false,
            infoText:
              'Contact vendor for setup time for your desired configuration.',
          },
        ],
      },
      {
        name: 'WILSCOT',
        logo: 'logos/wilscot.png',
        structure: 'hard-sided',
        products: [
          {
            id: 'wilscot-patient',
            name: 'Patient Unit',
            type: 'shelter',
            tested: false,
            infoText:
              'Per-unit interior floorspace not stated in the Portable Solution Catalog; inferred from unit footprint.',
          },
          {
            id: 'wilscot-staff',
            name: 'Staff Unit',
            type: 'shelter',
            tested: false,
            infoText:
              'Per-unit interior floorspace not stated in the Portable Solution Catalog; inferred from unit footprint.',
          },
        ],
      },
    ],
    // filter: structured values for the filtering feature (hand-authored per product).
    //   bedCapacity: number | { min, max } | { excluded: true }
    //   extSqFt:     number | { excluded: true }
    //   intSqFt:     number | { excluded: true }
    // Derive from the display strings: strip "~", take the leading sq ft; ranges use { min, max };
    // N/A or no usable number → { excluded: true }.
    // Rationale: see DESIGN_DECISIONS.md (filter semantics) — to be added in the docs pass.
    specs: {
      'blumed-2032': {
        bedCapacity: '10',
        extDims: "660 sq ft (20' × 33')",
        intDims: '650 sq ft',
        wind: '80 mph Sustained, 100 mph Gusts',
        snow: '15 lb. per sq ft (PSF)',
        fire: 'NFPA 701',
        setup: '30 minutes with 6 trained personnel',
        ground: 'Cement, Asphalt, Dirt',
        lifespan:
          'BLU-MED structures are designed and provide for extended erection of 10 years with a shelf life of 20 years',
        repair:
          '100 Setup/Strike Cycles – No System Failure. Each shelter includes (1) repair kit.',
        filter: {
          bedCapacity: 10,
          extSqFt: 660,
          intSqFt: 650,
        },
      },
      'blumed-2039': {
        bedCapacity: '10',
        extDims: "780 sq ft (20' × 39')",
        intDims: '780 sq ft',
        wind: '80 mph Sustained, 100 mph Gusts',
        snow: '15 lb. per sq ft (PSF)',
        fire: 'NFPA 701',
        setup: '30 minutes with 6 trained personnel',
        ground: 'Cement, Asphalt, Dirt',
        lifespan:
          'BLU-MED structures are designed and provide for extended erection of 10 years with a shelf life of 20 years',
        repair:
          '100 Setup/Strike Cycles – No System Failure. Each shelter includes (1) repair kit.',
        filter: {
          bedCapacity: 10,
          extSqFt: 780,
          intSqFt: 780,
        },
      },
      'dlx-asap18': {
        bedCapacity: '3',
        extDims: "288 sq ft (16' × 18')",
        intDims: '288 sq ft',
        wind: '55 mph sustained, 65 mph gusts',
        snow: '5 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '2 person; 1 minute under canopy, 10 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: 3,
          extSqFt: 288,
          intSqFt: 288,
        },
      },
      'dlx-x8': {
        bedCapacity: 'N/A',
        extDims: "176 sq ft (8' × 22')",
        intDims: '172 sq ft',
        wind: '65 mph sustained, 75 mph gusts',
        snow: '10 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '3 personnel; 15 minutes under canopy, 30 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: { excluded: true },
          extSqFt: 176,
          intSqFt: 172,
        },
      },
      'dlx-x16': {
        bedCapacity: '6',
        extDims: "352 sq ft (16' × 22')",
        intDims: '344 sq ft',
        wind: '65 mph sustained, 75 mph gusts',
        snow: '10 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '15 minutes under canopy, 30 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: 6,
          extSqFt: 352,
          intSqFt: 344,
        },
      },
      'dlx-x24': {
        bedCapacity: '8',
        extDims: "528 sq ft (22' × 24')",
        intDims: '516 sq ft',
        wind: '65 mph sustained, 75 mph gusts',
        snow: '10 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '4 person; 15 minutes under canopy, 30 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: 8,
          extSqFt: 528,
          intSqFt: 516,
        },
      },
      'dlx-x24sc': {
        bedCapacity: '6',
        extDims: "624 sq ft (24' × 26')",
        intDims: '531 sq ft',
        wind: '65 mph sustained, 75 mph gusts',
        snow: '10 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '4 person; 15 minutes under canopy, 40 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: 6,
          extSqFt: 624,
          intSqFt: 531,
        },
      },
      'dlx-x32': {
        bedCapacity: '12',
        extDims: "704 sq ft (22' × 32')",
        intDims: '688 sq ft',
        wind: '65 mph sustained, 75 mph gusts',
        snow: '10 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '5 person; 15 minutes under canopy, 30 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: 12,
          extSqFt: 704,
          intSqFt: 688,
        },
      },
      'dlx-x40': {
        bedCapacity: '14',
        extDims: "880 sq ft (22' × 40')",
        intDims: '860 sq ft',
        wind: '65 mph sustained, 75 mph gusts',
        snow: '10 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '6 person; 15 minutes under canopy, 30 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: 14,
          extSqFt: 880,
          intSqFt: 860,
        },
      },
      'dlx-xhub': {
        bedCapacity: null,
        extDims: "484 sq ft (22' × 22')",
        intDims: '484 sq ft',
        wind: '65 mph sustained, 75 mph gusts',
        snow: '10 lbs/sq ft',
        fire: 'NFPA 701',
        setup: '4 person; 15 minutes under canopy, 30 minutes full setup',
        ground: 'Flat, dry ground, asphalt, or concrete.',
        lifespan: '10 years if properly maintained',
        repair: 'Vinyl repairs may be needed if damaged during use. Repair kit included.',
        filter: {
          bedCapacity: { excluded: true },
          extSqFt: 484,
          intSqFt: 484,
        },
      },
      'hdt-305': {
        bedCapacity: '8',
        extDims: "525 sq ft (21' × 25')",
        intDims: '450 sq ft',
        wind: '55 mph constant and 65 mph gusts',
        snow: '10 lbs per sq ft',
        fire: 'CSFM 13115 Flame Retardant Fabric Registration',
        setup: '12 min with 4 people',
        ground:
          'Hard packed level ground with good drainage is preferred. Can also be setup on asphalt or concrete with add on hard surface anchoring system.',
        lifespan: '10+ years',
        repair:
          'Each shelter comes with repair kit for typical field repairs. Parts can be ordered as needed.',
        filter: {
          bedCapacity: 8,
          extSqFt: 525,
          intSqFt: 450,
        },
      },
      'hdt-8d36': {
        bedCapacity: '18',
        extDims: '~1184 sq ft (Dome)',
        intDims: '935 sq ft',
        wind: '55 mph constant and 65 mph gusts',
        snow: '10 lbs per sq ft',
        fire: 'CSFM 13115 Flame Retardant Fabric Registration',
        setup: '20 min with 8 people',
        ground:
          'Hard packed level ground with good drainage is preferred. Can also be setup on asphalt or concrete with add on hard surface anchoring system.',
        lifespan: '10+ years with proper care & maintenance',
        repair:
          'Each shelter comes with repair kit for typical field repairs. Parts can be ordered as needed.',
        filter: {
          bedCapacity: 18,
          extSqFt: 935,
          intSqFt: 935,
        },
      },
      'ws-gk20': {
        bedCapacity: 'N/A',
        extDims: '~286 sq ft (Octagon)',
        intDims: '~286 sq ft (Octagon)',
        wind: '55 mph constant and 65 mph gusts',
        snow: '10 lbs/sq ft for 12 hours',
        fire: 'NFPA 701',
        setup: '45 min w/ 6 people per shelter',
        ground: 'Hard & level (concrete, grass, dirt)',
        lifespan: '10+ years with proper care & maintenance',
        repair:
          'Yearly inspection & maintenance – parts can be ordered individually as needed.',
        filter: {
          bedCapacity: { excluded: true },
          extSqFt: 286,
          intSqFt: 286,
        },
      },
      'ws-gk1935': {
        bedCapacity: '10',
        extDims: '~630 sq ft (Clipped-corner rectangle)',
        intDims: '~570 sq ft',
        wind: '55 mph w/ gusts to 65 mph',
        snow: '10 lbs/sq ft for 12 hours',
        fire: 'NFPA 701',
        setup: '45 min w/ 12 people per shelter',
        ground: 'Hard & level (concrete, grass, dirt)',
        lifespan: '10+ years with proper care & maintenance',
        repair:
          'Yearly inspection & maintenance – parts can be ordered individually as needed.',
        filter: {
          bedCapacity: 10,
          extSqFt: 630,
          intSqFt: 570,
        },
      },
      'ws-gk2360': {
        bedCapacity: '22',
        extDims: '~1403 sq ft (Clipped-corner rectangle)',
        intDims: '1274 sq ft',
        wind: '55 mph w/gusts to 65 mph',
        snow: '10 lbs. / ft² for 12 hrs.',
        fire: 'NFPA 701',
        setup: '60 min w/ 12 people per shelter.',
        ground: 'Hard & level (concrete, grass, dirt)',
        lifespan: '10+ years with proper care & maintenance.',
        repair:
          'Yearly inspection & maintenance - parts can be ordered individually as needed.',
        filter: {
          bedCapacity: 22,
          extSqFt: 1403,
          intSqFt: 1274,
        },
      },
      'ws-gk2342': {
        bedCapacity: '17',
        extDims: '~966 sq ft (Clipped-corner rectangle)',
        intDims: '840 sq ft',
        wind: '55 mph w/gusts to 65 mph',
        snow: '10 lbs. / ft² for 12 hrs.',
        fire: 'NFPA 701',
        setup: '60 min w/ 12 people per shelter.',
        ground: 'Hard & level (concrete, grass, dirt)',
        lifespan: '10+ years with proper care & maintenance.',
        repair:
          'Yearly inspection & maintenance - parts can be ordered individually as needed.',
        filter: {
          bedCapacity: 17,
          extSqFt: 966,
          intSqFt: 840,
        },
      },
      'ws-guardian-2032': {
        bedCapacity: '14',
        extDims: "660 sq ft (20' × 33')",
        intDims: '650 sq ft',
        wind: '90 mph w/gusts to 120 mph',
        snow: '24 lbs. / ft² for 12 hrs.',
        fire: 'NFPA 701',
        setup: '30 min w/ 4 people per shelter.',
        ground: 'Hard & level (concrete, grass, dirt)',
        lifespan: '10+ years with proper care & maintenance.',
        repair:
          'Yearly inspection & maintenance - parts can be ordered individually as needed.',
        filter: {
          bedCapacity: 14,
          extSqFt: 660,
          intSqFt: 650,
        },
      },
      'ws-guardian-3065': {
        bedCapacity: '42',
        extDims: "1950 sq ft (30' × 65')",
        intDims: '1950 sq ft',
        wind: '90 mph w/gusts to 120 mph',
        snow: '24 lbs. / ft² for 12 hrs.',
        fire: 'NFPA 701',
        setup: '30 min w/ 4 people per shelter.',
        ground: 'Hard & level (concrete, grass, dirt)',
        lifespan: '10+ years with proper care & maintenance.',
        repair:
          'Yearly inspection & maintenance - parts can be ordered individually as needed.',
        filter: {
          bedCapacity: 42,
          extSqFt: 1950,
          intSqFt: 1950,
        },
      },
      'zumro-400': {
        bedCapacity: '6 to 8',
        extDims: "420 sq ft (20' × 21')",
        intDims: '400 sq ft',
        wind: '50 mph w/ gusts to 60 mph',
        snow: '3.51 lbs. per square foot STATIC load',
        fire: 'NFPA 701',
        setup: '5 minutes with 2 personnel',
        ground: 'Hard & Level Preferred',
        lifespan: '15+ years with proper maintenance & care',
        repair: 'Annual Inspections & Maintenance as needed',
        filter: {
          bedCapacity: { min: 6, max: 8 },
          extSqFt: 420,
          intSqFt: 400,
        },
      },
      'zumro-600': {
        bedCapacity: '10 to 12',
        extDims: "651 sq ft (21' × 31')",
        intDims: '600 sq ft',
        wind: '50 mph w/ gusts to 60 mph',
        snow: '3.29 lbs. per square foot STATIC load',
        fire: 'NFPA 701',
        setup: '5–7 minutes with 2 personnel',
        ground: 'Hard & Level Preferred',
        lifespan: '15+ years with proper maintenance & care',
        repair: 'Annual Inspections & Maintenance as needed',
        filter: {
          bedCapacity: { min: 10, max: 12 },
          extSqFt: 651,
          intSqFt: 600,
        },
      },
      'zumro-216': {
        bedCapacity: '4 to 8',
        extDims: "240 sq ft (15' × 16')",
        intDims: '216 sq ft',
        wind: '50 mph w/ gusts to 60 mph',
        snow:
          '3.44 lbs. per square foot STATIC load (Roof pitch specifically designed for snow/rain removal)',
        fire: 'NFPA 701',
        setup: '3 Minutes 1-2 Personnel',
        ground: 'Hard & Level Preferred',
        lifespan: '15+ years with proper maintenance & care',
        repair:
          'Annual Inspections & Maintenance as needed. ZUMRO replacement parts available through sales rep, online or website',
        filter: {
          bedCapacity: { min: 4, max: 8 },
          extSqFt: 240,
          intSqFt: 216,
        },
      },
      'zumro-900': {
        bedCapacity: '20 to 25',
        extDims: "990 sq ft (30' × 33')",
        intDims: '900 sq ft',
        wind: '50 mph w/ gusts to 60 mph',
        snow:
          '3.44 lbs. per square foot STATIC load (Roof pitch specifically designed for snow/rain removal)',
        fire: 'NFPA 701',
        setup: '5-7 Minutes 2-3 Personnel',
        ground: 'Hard & Level Preferred',
        lifespan: '15+ years with proper maintenance & care',
        repair:
          'Annual Inspections & Maintenance as needed. ZUMRO replacement parts available through sales rep, online or website',
        filter: {
          bedCapacity: { min: 20, max: 25 },
          extSqFt: 990,
          intSqFt: 900,
        },
      },
      'zumro-airlock': {
        bedCapacity: null,
        extDims: "88 sq ft (8' × 11')",
        intDims: '100 sq ft',
        wind: '50 mph w/ gusts to 60 mph',
        snow:
          '3.44 lbs. per square foot STATIC load (Roof pitch specifically designed for snow/rain removal)',
        fire: 'NFPA 701',
        setup: '2 Minutes 1 Personnel',
        ground: 'Hard & Level Preferred',
        lifespan: '15+ years with proper maintenance & care',
        repair:
          'Annual Inspections & Maintenance as needed. ZUMRO replacement parts available through sales rep, online or website',
        filter: {
          bedCapacity: { excluded: true },
          extSqFt: 88,
          intSqFt: 100,
        },
      },
      'zumro-quad': {
        bedCapacity: null,
        extDims: "~600 sq ft (20' × 30')",
        intDims: '454 sq ft',
        wind: '50 mph w/ gusts to 60 mph',
        snow: '3.44 lbs. per square foot STATIC load',
        fire: 'NFPA 701',
        setup: '5–7 minutes with 2 personnel',
        ground: 'Hard & Level Preferred',
        lifespan: '15+ Years with proper maintenance & care',
        repair: 'Annual Inspections & Maintenance as needed. ZUMRO replacement parts available through sales rep, online or website',
        filter: {
          bedCapacity: { excluded: true },
          extSqFt: 570,
          intSqFt: 454,
        },
      },
      'craftsmen-8bed-icu': {
        bedCapacity: '8',
        extDims: "1219 sq ft (23' × 53')",
        intDims: '1010 sq ft',
        wind: '100 mph anchored',
        snow: '40 lbs / ft2',
        fire: 'Materials have a rating, the trailer assembly is not rated',
        setup: '4 hours, 6 Personnel',
        ground:
          'Level, Hard Surface. Manually controlled hydraulic leveling system',
        lifespan: '10 years',
        repair:
          'Call Craftsmen at 1-800-373-3575 and request Customer Service Department',
        filter: {
          bedCapacity: 8,
          extSqFt: 1219,
          intSqFt: 1010,
        },
      },
      'forts-38': {
        bedCapacity: '~2 to 3',
        extDims: "360 sq ft (18' × 20')",
        intDims: '273 sq ft',
        wind: '180 mph anchored',
        snow: '30-40 lbs / ft2',
        fire:
          'Class “A” Spread of Flame for exterior fire resistance, per ASTM E108-07A, Southwest Research, Department of Fire Technology.',
        setup: 'Contact vendor',
        ground: 'Rough terrain capable on uneven, steep slope environments',
        lifespan: '10 years',
        repair: 'Call FORTS USA customer service at 954-949-3200',
        filter: {
          bedCapacity: { min: 2, max: 3 },
          extSqFt: 360,
          intSqFt: 273,
        },
      },
      'wilscot-patient': {
        bedCapacity: '6',
        extDims: "1440 sq ft (24' × 60')",
        intDims: '~1440 sq ft',
        wind: '140 mph anchored',
        snow: '50 lbs / ft2',
        fire: 'IBC V-B (Variance or Modification Required)',
        setup: 'Ranges by number of structures (~2 weeks)',
        ground:
          'Level, Hard Surface. Foundation (typically piers and footings) must be approved by a licensed professional engineer.',
        lifespan: '20-30 years',
        repair: 'Contract with Willscot or 3rd party vendor',
        filter: {
          bedCapacity: 6,
          extSqFt: 1440,
          intSqFt: 1440,
        },
      },
      'wilscot-staff': {
        bedCapacity: 'N/A',
        extDims: "720 sq ft (12' × 60')",
        intDims: '~720 sq ft',
        wind: '140 mph anchored',
        snow: '50 lbs / ft2',
        fire: 'IBC V-B (Variance or Modification Required)',
        setup: 'Ranges by number of structures (~2 weeks)',
        ground:
          'Level, Hard Surface. Foundation (typically piers and footings) must be approved by a licensed professional engineer.',
        lifespan: '20-30 years',
        repair: 'Contract with Willscot or 3rd party vendor',
        filter: {
          bedCapacity: { excluded: true },
          extSqFt: 720,
          intSqFt: 720,
        },
      },
    },
  };
})();
